version: "3"
services:
  app:
    build: .
    container_name: mel-michael/fraud-detector-app
    restart: always
    ports:
      - "4200:4200"
      - "5000:5000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"